
FROM python:3.4-alpine

ADD . /code

WORKDIR /code

ENV http_proxy http://10.232.233.70:8080
ENV https_proxy http://10.232.233.70:8080

RUN pip install -r requirements.txt

CMD ["python", "app.py"]


docker build -t myapp .