version: '3.2'
services:
  web:
    build: .
    ports:
     - "5000:80"
    volumes:
     - .:/code
  redis:
    image: "redis:alpine"
  portainer:
    image: portainer/portainer
    hostname: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock